version: '3.3'
services:
    postgres:
        image: postgres:13.5
        restart: always
        hostname: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres_123
            POSTGRES_DB: dundts
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - '15432:5432'
volumes:
    postgres: